[versions]
agp = "8.13.2"
datastorePreferences = "1.2.0"
kotlin = "2.3.0"
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2026.01.00"
koinBOM = "4.1.1"
koinKSP = "2.3.0"
ksp = "2.3.4"
accompanist = "0.37.3"
liteRT = "1.4.1"
liteRTExtensions = "1.4.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
accompanist-drawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBOM" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koinKSP" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinKSP" }

litert = { module = "com.google.ai.edge.litert:litert", version.ref = "liteRT"}
litert-support-api = { module = "com.google.ai.edge.litert:litert-support-api", version.ref = "liteRTExtensions" }
litert-gpu = { module = "com.google.ai.edge.litert:litert-gpu", version.ref = "liteRTExtensions" }
litert-gpu-api = { module = "com.google.ai.edge.litert:litert-gpu-api", version.ref = "liteRTExtensions" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

